# Generated by Django 5.1.1 on 2024-09-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_youtubevideo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeplaylist',
            name='title',
        ),
    ]
