# Generated by Django 5.1.1 on 2024-09-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_youtubeplaylist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeplaylist',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
